refactor: indexer
Crossbell-Box/crossbell.js pull request #22
Opened 2023-04-14 20:28 UTC by sxzz

Merge after #21

2023-04-16 08:04 UTC, Songkeys commented
Great. Just some naming issue.

2023-04-16 08:05 UTC, Songkeys requested changes

2023-04-16 08:05 UTC, Songkeys commented on src/indexer/subapis/stat.ts
> +  getByCharacter(characterId: Numberish) {
Of, or for.

2023-04-16 08:05 UTC, Songkeys commented on src/indexer/subapis/stat.ts
> +  getByNote(characterId: Numberish, noteId: Numberish) {
Of, or for

2023-04-16 08:05 UTC, Songkeys commented on src/indexer/subapis/notification.ts
> +  getManyByCharacter(
getMany should be fine as we don't have any alternative.

2023-04-16 08:05 UTC, Songkeys commented on src/indexer/subapis/minted_note.ts
> +  getManyByAddress(
Of

2023-04-16 08:05 UTC, Songkeys commented on src/indexer/subapis/minted_note.ts
> +  getManyByNote(
Of

2023-04-16 19:24 UTC, sxzz commented
Done

2023-04-17 04:46 UTC, Songkeys commented on src/indexer/subapis/base.ts
> +      if (r.status !== 200) {
use `res.ok` for all 20X status

2023-04-17 04:47 UTC, Songkeys requested changes
One more change.

2023-04-17 05:42 UTC, merged